### PR TITLE
Switch digital dtype to int32.

### LINKED ISSUE #54: PR #44 seems to be causing test failures
Was PR #44 tested in Python 3? When I run test_edfwriter.py in py3 I see:

`ValueError: Buffer dtype mismatch, expected 'int32_t' but got 'long'
`
This seems to stem from `blockwrite_digital_samples` in _pyedflib.pyx explicitly expecting int32, but np.int (equivalently the builtin int) in python has a version-dependent underlying dtype.

Does using np.int32 make more sense here?

### PR DESCRIPTION
**Pull request by dthkao**
Fixes #54

### CODE REVIEW

**Comment by dthkao** [comment]
friendly ping?

**Comment by snbarr** [comment]
Hi, thank you for providing an excellent library.  I noticed that the read_edf also needs to be changed to int32 on line 365 of highlevel.py for the anonymize_edf function to work.

**Comment by skjerns** [comment]
@snbarr feel free to make a PR/issue . 

PS the reference doesnt seem to work, https://github.com/holgern/pyedflib/blob/d7faabf9ef7edc7db0a953b5ba1e19d9f973db1f/pyedflib/highlevel.py#L365

**Comment by snbarr** [comment]
I think there is already an issue for this.  https://github.com/holgern/pyedflib/issues/54  Basically what happens is that read_edf uses int and write_edf expects int32.  I'm not sure why int isn't working, but when I change the line below to int32 it works.

https://github.com/skjerns/pyedflib/blob/ec6ec41513dd6db13479e28d2ed82fbafabe90e8/pyedflib/highlevel.py#L365

https://github.com/holgern/pyedflib/blob/d7faabf9ef7edc7db0a953b5ba1e19d9f973db1f/pyedflib/highlevel.py#L368

**Pull request merged**
