### PR TITLE
PyEdflib

### PR DESCRIPTION
**Pull request by deepa861**
import pyedflib
import numpy as np
import os

file_name = pyedflib.data.test_generator()
n = file_name.signals_in_file
signal_labels = file_name.getSignalLabels()
sigbufs = np.zeros((n, file_name.getNSamples()[0]))
for i in np.arange(n):
    sigbufs[i, :] = file_name.readSignal(i)

### CODE REVIEW

**Comment by skjerns** [comment]
what is the advantage of this?

**Comment by deepa861** [comment]
> what is the advantage of this? does this fix anything that didn't work before?

yes.previously getting an error when running original code

**Review by deepa861 — COMMENTED** [review]
import pyedflib
import numpy as np
import os

file_name = pyedflib.data.test_generator()
n = file_name.signals_in_file
signal_labels = file_name.getSignalLabels()
sigbufs = np.zeros((n, file_name.getNSamples()[0]))
for i in np.arange(n):
    sigbufs[i, :] = file_name.readSignal(i)

**Comment by skjerns** [comment]
Ah, now I think I understand what you mean. 

You mean the excerpt in the documentation, right? 

https://pyedflib.readthedocs.io/en/latest/

**Pull request closed without merging**
