### PR TITLE
Run tests on Python 3.10

### PR DESCRIPTION
**Pull request by cbrnr**
Added Python 3.10 to the test matrix.

### CODE REVIEW

**Comment by cbrnr** [comment]
I'm not sure why the GitHub actions do not run, but maybe because I don't have permission?

**Comment by cbrnr** [comment]
I changed all CIs I found, not sure which ones are really used 😄.

**Comment by skjerns** [comment]
> I'm not sure why the GitHub actions do not run, but maybe because I don't have permission?

they are not running as I incidentially rerun some other jobs that blocked them. Now they should run.

**Comment by cbrnr** [comment]
> however, the 3.10 wheel building doesn't seem to run, it hangs and then timeouts :-/

Can you try to restart this job?

**Comment by skjerns** [comment]
> > however, the 3.10 wheel building doesn't seem to run, it hangs and then timeouts :-/
> 
> Can you try to restart this job?

That's what I did, but it keeps hanging. No idea why.

**Comment by cbrnr** [comment]
> It throws an error about some import from collections, that needs to be fixed first. probably we need to use a newer version of nose or somtheing

OK. Maybe switching to Pytest would be an option?

**Comment by hofaflo** [comment]
Tested locally on Win10 with Python3.10, pytest works without any configuration and yields the same warnings as nose does on the lower Python versions, so you could try this:

In [appveyor.yml](https://github.com/holgern/pyedflib/blob/master/appveyor.yml), replace this

```yml
install:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install --upgrade pip"
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install --upgrade wheel"
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install
     Cython nose coverage numpy dateparser tqdm --cache-dir c:\\tmp\\pip-cache"

test_script:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe setup.py build --build-lib build\\lib\\"
  - "%PYTHON%\\Scripts\\nosetests build\\lib --tests pyedflib\\tests"
```

with this


```yml
install:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install --upgrade pip"
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install --upgrade wheel"
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install
     Cython pytest coverage numpy dateparser tqdm --cache-dir c:\\tmp\\pip-cache"

test_script:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\Scripts\\pytest"
```

**Comment by cbrnr** [comment]
Thanks @hofaflo, let's see if this works.

**Comment by cbrnr** [comment]
Yay, this worked!

**Comment by skjerns** [comment]
perfect! I'll merge :)

I always use `pytest` locally anyway, not sure why some of them were still running with nose.

**Comment by cbrnr** [comment]
Now about that release 😄 - is there anything still missing?

**Comment by skjerns** [comment]
From our side no - just the sudo powers of @holgern 😀 (I don't have access to pipy)

however, I'm currently working on resolving #148 , so give me another day or two, as that will be a major change that should be included in a next release.

**Pull request merged**
